# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sql_service.proto\x12\x0bsql_service\x1a\x1egoogle/protobuf/wrappers.proto\"E\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12&\n\x08\x62indings\x18\x02 \x03(\x0b\x32\x14.sql_service.Binding\"\xdc\x01\n\x07\x42inding\x12\x34\n\x0cstring_value\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x12\x30\n\tint_value\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueH\x00\x12\x30\n\nbool_value\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.BoolValueH\x00\x12,\n\nnull_value\x18\x04 \x01(\x0e\x32\x16.sql_service.NullValueH\x00\x42\t\n\x07\x62inding\"/\n\rQueryResponse\x12\x1e\n\x04rows\x18\x01 \x03(\x0b\x32\x10.sql_service.Row\"(\n\x03Row\x12!\n\x05value\x18\x01 \x03(\x0b\x32\x12.sql_service.Value\"\x8c\x02\n\x05Value\x12\x34\n\x0cstring_value\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x12\x30\n\tint_value\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueH\x00\x12\x30\n\nbool_value\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.BoolValueH\x00\x12,\n\nnull_value\x18\x04 \x01(\x0e\x32\x16.sql_service.NullValueH\x00\x12\x32\n\x0b\x66loat_value\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.FloatValueH\x00\x42\x07\n\x05value*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x32U\n\nSQLService\x12G\n\x0c\x45xecuteQuery\x12\x19.sql_service.QueryRequest\x1a\x1a.sql_service.QueryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sql_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NULLVALUE']._serialized_start=722
  _globals['_NULLVALUE']._serialized_end=749
  _globals['_QUERYREQUEST']._serialized_start=66
  _globals['_QUERYREQUEST']._serialized_end=135
  _globals['_BINDING']._serialized_start=138
  _globals['_BINDING']._serialized_end=358
  _globals['_QUERYRESPONSE']._serialized_start=360
  _globals['_QUERYRESPONSE']._serialized_end=407
  _globals['_ROW']._serialized_start=409
  _globals['_ROW']._serialized_end=449
  _globals['_VALUE']._serialized_start=452
  _globals['_VALUE']._serialized_end=720
  _globals['_SQLSERVICE']._serialized_start=751
  _globals['_SQLSERVICE']._serialized_end=836
# @@protoc_insertion_point(module_scope)
